version: '3'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
